### ISSUE TITLE
no WETH

### ISSUE THREAD

**Issue by povertyhacked** [avnu-labs/avnu-contracts#11]
i cant see any option to swap with WETH

**Comment by 0xMentorNotAPseudo** [comment]
Hi,

WETH isn't an asset available on Starknet. That's why(See Starkgate for a better reference of available tokens on Starknet).

P.S: please don't hesitate to use more relevant channels for this kind of feedback. Last but not least, this is not the latest AVNU contract repository (we should deprecate it)
